#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 900
#define SCREEN_HEIGHT 600

#define CELL_SIZE 10
#define COLUMNS SCREEN_WIDTH/CELL_SIZE
#define LINE_WIDTH 2
#define ROWS SCREEN_HEIGHT/CELL_SIZE

#endif
